# Step 1: Use Node 20 alpine image
FROM node:24-alpine

WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .
EXPOSE 3000

# Step 7: Run Vite dev server, accessible from outside Docker
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]