# .gitlab-ci.yml
stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - self-hosted # optional: only if your runner has this tag
  script:
    - echo "Deploying application..."
    - cd /home/abdullah/to-do-app
    - docker compose down
    - docker compose build
    - docker compose up -d --remove-orphans
  only:
    - main
    - master
