stages:
  - build
  - deploy

variables:
  DEPLOY_SERVER: "ubuntu@13.53.200.88"
  DEPLOY_PATH: "/home/ubuntu/todo-app"
  IMAGE_NAME_BACKEND: "ghcr.io/arham1716/todo-backend"
  IMAGE_NAME_FRONTEND: "ghcr.io/arham1716/todo-frontend"

# Step 1: Build Docker images and push to registry
build:
  stage: build
  tags:
    - self-hosted
  script:
    # Docker login to GHCR
    - echo "$REGISTRY_TOKEN" | docker login ghcr.io -u "$REGISTRY_USER" --password-stdin

    - echo "Building backend image..."
    - docker build -t $IMAGE_NAME_BACKEND:$CI_COMMIT_SHA ./backend
    - docker tag $IMAGE_NAME_BACKEND:$CI_COMMIT_SHA $IMAGE_NAME_BACKEND:latest
    - docker push $IMAGE_NAME_BACKEND:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME_BACKEND:latest

    # Frontend
    - echo "Building frontend image..."
    - docker build -t $IMAGE_NAME_FRONTEND:$CI_COMMIT_SHA ./frontend
    - docker tag $IMAGE_NAME_FRONTEND:$CI_COMMIT_SHA $IMAGE_NAME_FRONTEND:latest
    - docker push $IMAGE_NAME_FRONTEND:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME_FRONTEND:latest
  only:
    - main
    - master

# Step 2: Deploy on Messam's VM
deploy:
  stage: deploy
  tags:
    - self-hosted

  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 13.53.200.88 >> ~/.ssh/known_hosts

  script:
    # Create folder if not exists
    - ssh ubuntu@13.53.200.88 "mkdir -p ~/todo-app"

    # Copy files
    - scp docker-compose.yml ubuntu@13.53.200.88:~/todo-app/
    - scp nginx.conf ubuntu@13.53.200.88:~/todo-app/

    # Deploy
    - |
      ssh ubuntu@13.53.200.88 "
      cd ~/todo-app &&
      docker compose pull &&
      docker compose up -d --remove-orphans
      "
  only:
    - main
    - master
    - merge_requests
