stages:
  - build
  - deploy

variables:
  DEPLOY_PATH: "/home/messam/to-do-app"
  DEPLOY_SERVER: "messam@172.28.5.10"
  IMAGE_NAME_BACKEND: "ghcr.io/arham1716/todo-backend"
  IMAGE_NAME_FRONTEND: "ghcr.io/arham1716/todo-frontend"

# Step 1: Build Docker images and push to registry
build:
  stage: build
  tags:
    - self-hosted
  script:
    # Docker login to GHCR
    - echo "$REGISTRY_TOKEN" | docker login ghcr.io -u "$REGISTRY_USER" --password-stdin

    - echo "Building backend image..."
    - docker build -t $IMAGE_NAME_BACKEND:$CI_COMMIT_SHA ./backend
    - docker tag $IMAGE_NAME_BACKEND:$CI_COMMIT_SHA $IMAGE_NAME_BACKEND:latest
    - docker push $IMAGE_NAME_BACKEND:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME_BACKEND:latest

    # Frontend
    - echo "Building frontend image..."
    - docker build -t $IMAGE_NAME_FRONTEND:$CI_COMMIT_SHA ./frontend
    - docker tag $IMAGE_NAME_FRONTEND:$CI_COMMIT_SHA $IMAGE_NAME_FRONTEND:latest
    - docker push $IMAGE_NAME_FRONTEND:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME_FRONTEND:latest
  only:
    - main
    - master

# Step 2: Deploy on Messam's VM
deploy:
  stage: deploy
  tags:
    - self-hosted
  script:
    - scp -o StrictHostKeyChecking=no docker-compose.yml $DEPLOY_SERVER:$DEPLOY_PATH
    - |
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $DEPLOY_SERVER "
      cd $DEPLOY_PATH &&
      docker compose pull &&
      docker compose up -d --remove-orphans
      "
  only:
    - main
    - master
    - merge_requests
