name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          cd /home/abdullah/to-do-app
          docker compose down
          docker compose build
          docker compose up -d --remove-orphans
